# Generated by Django 3.1.6 on 2021-02-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=300, upload_to='img'),
            preserve_default=False,
        ),
    ]
